name: Data Integration Test

#Trigger workflow on push to the main branch
on:
    push:
      paths:
        - "data-hub/**"
    workflow_dispatch: 
      branches:
          - main

jobs:
    integrate-data:
         runs-on: ubuntu-latest

         steps:
         - name: Checkout repository 
           uses: actions/checkout@v3

         - name: Run Data Integration Script 
           run: bash ./integration.sh

          
